# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: lightwell-network-ui-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: lightwell-network-ui
    spec:
      feoConfigEnabled: true
      # TODO: add serviceTiles and searchEntries for lightwell
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: LightwellNetworkUI
      deploymentRepo: https://github.com/lightwell-network/lightwell-network-frontend
      frontend:
        paths:
          - /apps/lightwell-network-ui
      image: ${IMAGE}:${IMAGE_TAG}
      pushCacheEnabled: true

      module:
        manifestLocation: '/apps/lightwell-network-ui/fed-mods.json'
        modules:
          - id: 'lightwell-network-ui'
            module: './RootApp'
            routes:
              - pathname: /staging/lightwell # TODO: confirm temporary route for lightwell tenant to use during onboarding
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/lightwell-network-ui-tenant/lightwell-network-ui/lightwell-network-ui-frontend
